# Generated by Django 3.0.3 on 2020-05-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20200526_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='run.UserInfo'),
        ),
    ]
