# Generated by Django 3.0.3 on 2020-05-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_auto_20200526_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/', verbose_name='图片')),
                ('rank', models.IntegerField()),
                ('applied_by', models.IntegerField()),
                ('is_checked', models.IntegerField(default=0)),
                ('checked_by', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Common'), (2, 'Admini')], default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run.UserInfo')),
            ],
        ),
    ]
