# Generated by Django 3.0.3 on 2020-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_auto_20200530_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankinfo',
            name='image',
            field=models.BinaryField(),
        ),
    ]
